name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "1 * * * *"

jobs:
  update-readme:
    name: Update WakaReadme Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: athul/waka-readme@master
        with:
          API_BASE_URL: ${{ secrets.WAKAPI_BASE_URL }}
          WAKATIME_API_KEY: ${{ secrets.WAKAPI_API_KEY }}

          TIME_RANGE: last_30_days
          SHOW_TIME: true
          BLOCKS: "⬜🟨🟩"

          COMMIT_MESSAGE: "Update Wakapi stats"
